### ISSUE TITLE
Getting a success AND error message at the same time

### ISSUE THREAD

**Issue by marcondag** [debtcollective/parent#63]
After you finish the Dispute creation process, you get success and error messages at the same time.

![image](https://user-images.githubusercontent.com/849872/45002970-aefa4480-afa2-11e8-9519-ce716f5fb8d1.png)

Some Promises inside the DisputesController don't catch errors, and this may be the issue.

## Tasks

- [ ] Research why the error message is coming up
- [ ] Write a small spec with the cause and proposed solution

## Acceptance criteria

- The bug is fixed

**Comment by orlando** [comment]
This happens when imagemagick fails to start, but we now don't have imagemagick and the error handling is better since @marcondag rewrote this part.

I think we can close this now

**Comment by shoshber** [comment]
Opening this again because testing in staging by back office revealed that it still happens sometimes. 

https://github.com/debtcollective/parent/issues/63

**Comment by marcondag** [comment]
Just had this happen and here is the stack trace in the logs

```error: Unable to mark dispute as completed Dispute.query is not a function TypeError: Dispute.query is not a function
    at newClass.buildZip (/Users/alex/DebtCollective/dispute-tools/models/DisputeRenderer.js:104:39)
    at DisputeRenderer.query.where.include.then (/Users/alex/DebtCollective/dispute-tools/models/Dispute.js:296:37)
    at bound (domain.js:301:14)
    at runBound (domain.js:314:12)
    at tryCatcher (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:638:18)
    at PromiseArray._resolve (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise_array.js:126:19)
    at PromiseArray._promiseFulfilled (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise_array.js:144:14)
    at PromiseArray._iterate (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise_array.js:114:31)
    at PromiseArray.init [as _init] (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise_array.js:78:10)
    at bound (domain.js:301:14)
    at PromiseArray.runBound (domain.js:314:12)
    at Promise._settlePromise (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/alex/DebtCollective/dispute-tools/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)```
